version: '3.9'

services:
  app:
    container_name: app
    platform: linux/amd64
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    ports:
      - "${APP_PORT}:3000"
    environment:
      MONGO_URL: "mongodb://mongo:${MONGO_PORT}/${MONGO_INITDB_DATABASE}"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq"
      MAILHOG_HOST: "mailhog:${MAILHOG_SMTP_PORT}"
    depends_on:
      - mongo
      - rabbitmq
      - mailhog
    volumes:
      - .:/app
      - node_modules:/app/node_modules

  mongo:
    container_name: mongo
    platform: linux/amd64
    image: mongo:4.0
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    container_name: mongo-express
    platform: linux/amd64
    image: mongo-express
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  mailhog:
    container_name: mailhog
    platform: linux/amd64
    image: mailhog/mailhog
    ports:
      - "${MAILHOG_WEB_PORT}:8025" # Web interface
      - "${MAILHOG_SMTP_PORT}:1025" # SMTP server

  rabbitmq:
    container_name: rabbitmq
    platform: linux/amd64
    image: "rabbitmq:management"
    ports:
      - "${RABBITMQ_AMQP_PORT}:5672" # AMQP protocol
      - "${RABBITMQ_MANAGEMENT_PORT}:15672" # Management interface
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mongo_data:
  rabbitmq_data:
  node_modules:
